# Generated by Django 4.1.2 on 2022-10-30 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Concepto_pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CuentasXcobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=300)),
                ('Concepto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.concepto_pagos')),
                ('alumno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.alumno')),
            ],
        ),
    ]
