# Generated by Django 4.1.3 on 2022-11-18 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('fotografia', models.ImageField(null=True, upload_to='fotografias')),
                ('certificado', models.ImageField(null=True, upload_to='certificados')),
                ('comprobante', models.ImageField(null=True, upload_to='comprobantes')),
            ],
        ),
        migrations.CreateModel(
            name='Concepto_pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRIPCION', models.CharField(max_length=300)),
                ('acuerdo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CuentasXcobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=300)),
                ('alumno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.alumno')),
                ('concepto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.concepto_pagos')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.plan'),
        ),
    ]
