# Generated by Django 4.1.3 on 2022-11-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuentasxcobrar',
            old_name='Concepto_id',
            new_name='concepto_id',
        ),
        migrations.AddField(
            model_name='alumno',
            name='fotografia',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
