# Generated by Django 4.1.3 on 2022-11-23 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referencias_pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField()),
                ('total_pagar', models.IntegerField()),
                ('referencia', models.CharField(max_length=30)),
                ('alumno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.alumno')),
                ('concepto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.concepto_pagos')),
            ],
        ),
    ]
