# Generated by Django 4.1.3 on 2022-11-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_rename_concepto_id_cuentasxcobrar_concepto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fotografia',
            field=models.ImageField(null=True, upload_to='fotografias'),
        ),
    ]
