# Generated by Django 4.1.3 on 2022-11-25 16:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_alter_referencias_pagos_concepto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='correo_electronico',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referencias_pagos',
            name='anio_concepto',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referencias_pagos',
            name='estado',
            field=models.CharField(default='Por pagar', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referencias_pagos',
            name='mes_concepto',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Estatus_doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_doc', models.CharField(max_length=100)),
                ('estatus', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('observaciones', models.CharField(max_length=1000)),
                ('alumno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.alumno')),
            ],
        ),
    ]
