# Generated by Django 4.1.3 on 2022-11-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_alumno_correo_electronico_alumno_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='referencias_pagos',
            name='anio_concepto',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='referencias_pagos',
            name='estado',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='referencias_pagos',
            name='mes_concepto',
            field=models.IntegerField(null=True),
        ),
    ]
